/**
 * Curriculum Types
 *
 * Types for multi-article learning paths (curricula) in the Learn tab.
 * Curricula contain 3-10 articles that progressively build knowledge on a topic.
 */

import { ArticleTone } from './generated';
import { Question } from './learning';

// =============================================================================
// Constants
// =============================================================================

/** Minimum number of articles in a curriculum */
export const ARTICLE_COUNT_MIN = 3;

/** Maximum number of articles in a curriculum */
export const ARTICLE_COUNT_MAX = 10;

/** Minimum word count per article */
const WORD_COUNT_MIN = 500;

/** Maximum word count per article */
const WORD_COUNT_MAX = 5000;

// =============================================================================
// Status Types
// =============================================================================

/**
 * Generation status for a curriculum article.
 * - pending: Not yet generated
 * - generating: Currently being generated by LLM
 * - generated: Successfully generated
 * - failed: Generation failed (check generationError)
 */
export type ArticleGenerationStatus = 'pending' | 'generating' | 'generated' | 'failed';

/**
 * Completion status for a curriculum article.
 * - locked: Cannot be read yet (previous article not completed)
 * - unlocked: Can be read, not yet started
 * - in_progress: Currently being read
 * - completed: Quiz completed
 */
export type ArticleCompletionStatus = 'locked' | 'unlocked' | 'in_progress' | 'completed';

// =============================================================================
// Article Types
// =============================================================================

/**
 * A single article within a curriculum.
 * Articles are generated by the LLM based on the curriculum outline.
 */
export interface CurriculumArticle {
  /** Unique identifier (format: {curriculumId}-article-{orderIndex}) */
  id: string;

  /** Parent curriculum ID */
  curriculumId: string;

  /** Position in curriculum (0-indexed) */
  orderIndex: number;

  /** Article title (from outline or generated) */
  title: string;

  /** Brief summary of article content */
  summary: string;

  /** Full article content (empty until generated) */
  content: string;

  /** Word count of the content */
  wordCount: number;

  /** Whether this article should include a quiz (inherited from curriculum) */
  hasQuiz: boolean;

  /** Comprehension questions for the article */
  questions: Question[];

  /** Current generation status */
  generationStatus: ArticleGenerationStatus;

  /** Current completion status (for user progress) */
  completionStatus: ArticleCompletionStatus;

  /** Timestamp when content was generated */
  generatedAt?: number;

  /** Timestamp when generation started (for stale detection) */
  generationStartedAt?: number;

  /** Timestamp when user completed the article */
  completedAt?: number;

  /** User's comprehension score (0-100) */
  comprehensionScore?: number;

  /** User's reading WPM for this article */
  readingWPM?: number;

  /** Error message if generation failed */
  generationError?: string;
}

// =============================================================================
// Outline Types
// =============================================================================

/**
 * Article outline generated by LLM during curriculum creation.
 * Contains the structure but not the full content.
 */
export interface CurriculumOutlineArticle {
  /** Position in curriculum (0-indexed) */
  orderIndex: number;

  /** Article title */
  title: string;

  /** Brief summary of what this article covers */
  summary: string;

  /** Key concepts this article will introduce */
  keyConceptsToIntroduce: string[];

  /** Concepts from earlier articles that this article builds upon */
  prerequisiteConcepts: string[];
}

/**
 * Curriculum outline generated by LLM.
 * Defines the structure of all articles before content generation.
 */
export interface CurriculumOutline {
  /** Overall curriculum title */
  curriculumTitle: string;

  /** Outline for each article */
  articles: CurriculumOutlineArticle[];
}

// =============================================================================
// Curriculum Types
// =============================================================================

/**
 * A complete curriculum with all articles.
 */
export interface Curriculum {
  /** Unique identifier (format: curr_{timestamp}_{random}) */
  id: string;

  /** Curriculum title (from outline) */
  title: string;

  /** User's learning goal (what they want to learn) */
  goal: string;

  /** Number of articles in curriculum */
  articleCount: number;

  /** Writing tone for all articles */
  tone: ArticleTone;

  /** Target word count per article */
  targetWordCount: number;

  /** Whether articles in this curriculum include comprehension quizzes */
  hasQuizzes: boolean;

  /** Timestamp when curriculum was created */
  createdAt: number;

  /** Timestamp of last update */
  updatedAt: number;

  /** Index of current/next article to read */
  currentArticleIndex: number;

  /** Number of articles completed */
  completedArticleCount: number;

  /** Whether all articles have been completed */
  isCompleted: boolean;

  /** Curriculum outline (set after outline generation) */
  outline?: CurriculumOutline;

  /** All articles in the curriculum */
  articles: CurriculumArticle[];

  /** Optional: Article range used during generation (V2 only) */
  articleRange?: { min: number; max: number };

  /** Optional: Duration range used during generation (V2 only) */
  durationRange?: { min: number; max: number };
}

// =============================================================================
// Input Types
// =============================================================================

/**
 * Input for creating a new curriculum.
 * @deprecated Use CurriculumCreationInputV2 for new implementations
 */
export interface CurriculumCreationInput {
  /** Learning goal (what the user wants to learn) */
  goal: string;

  /** Number of articles (3-10) */
  articleCount: number;

  /** Writing tone for articles */
  tone: ArticleTone;

  /** Target reading duration per article (in minutes) */
  durationMinutes: number;

  /** Whether to generate quiz questions for articles (optional, defaults to true) */
  hasQuizzes?: boolean;
}

/**
 * Input for creating a new curriculum (V2 - Portion-based).
 * Supports article ranges where LLM decides optimal count within range.
 */
export interface CurriculumCreationInputV2 {
  /** Learning goal (what the user wants to learn) */
  goal: string;

  /** Article count range (LLM decides within range) */
  articleRange: { min: number; max: number };

  /** Writing tone for articles or 'auto' for LLM decision */
  tone: ArticleTone | 'auto';

  /** Duration range in minutes (LLM decides optimal duration within range) */
  durationRange: { min: number; max: number };

  /** Whether to generate quiz questions for articles (optional, defaults to true) */
  hasQuizzes?: boolean;
}

// =============================================================================
// API Types
// =============================================================================

/**
 * Request body for curriculum outline generation API.
 */
export interface GenerateOutlineRequest {
  goal: string;
  articleCount: number;
  tone: string;
  tonePrompt: string;
}

/**
 * Response from curriculum outline generation API.
 */
export interface GenerateOutlineResponse {
  success: boolean;
  outline?: CurriculumOutline;
  error?: string;
  errorCode?: 'INVALID_REQUEST' | 'GENERATION_FAILED';
}

/**
 * Curriculum context passed to article generation API.
 * Provides context for generating articles within a curriculum.
 */
export interface CurriculumContext {
  curriculumTitle: string;
  articleTitle: string;
  articleSummary: string;
  keyConceptsToIntroduce: string[];
  prerequisiteConcepts: string[];
  previousArticleSummary: string | null;
  position: string; // e.g., "1 of 5"
}

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Validates that article count is within allowed range (3-10).
 */
export function isValidArticleCount(count: number): boolean {
  return Number.isInteger(count) && count >= ARTICLE_COUNT_MIN && count <= ARTICLE_COUNT_MAX;
}

/**
 * Calculates target word count from reading duration and WPM.
 * Enforces minimum (500) and maximum (5000) word counts.
 *
 * @param durationMinutes - Target reading duration in minutes
 * @param avgWpm - User's average words per minute (default: 250)
 * @returns Target word count, clamped to 500-5000 range
 */
export function durationToWordCount(durationMinutes: number, avgWpm: number = 250): number {
  const targetWords = Math.round(durationMinutes * avgWpm);
  return Math.max(WORD_COUNT_MIN, Math.min(WORD_COUNT_MAX, targetWords));
}

/**
 * Determines if a quiz icon should be shown for an article.
 * Returns true only if the article is configured to have a quiz AND has questions.
 *
 * @param article - The curriculum article to check
 * @returns True if quiz icon should be displayed
 */
export function shouldShowQuizIcon(article: CurriculumArticle): boolean {
  return article.hasQuiz && article.questions.length > 0;
}

/**
 * Determines if quiz generation failed for an article.
 * Returns true if quiz was expected but generation failed.
 *
 * @param article - The curriculum article to check
 * @returns True if quiz generation failed
 */
export function hasQuizGenerationFailed(article: CurriculumArticle): boolean {
  return (
    article.hasQuiz &&
    article.generationStatus === 'failed' &&
    article.questions.length === 0
  );
}
